=== xbacinsk/MZJ_Timetable/misc/timetable.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:simpleType name="hourValueType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}:[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="hourType">
        <xs:simpleContent>
            <xs:extension base="hourValueType">
                <xs:attribute name="pdiff" type="xs:positiveInteger" use="required"/>
                <xs:attribute name="diff" type="xs:positiveInteger" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="oneAttributeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="timetable">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hours">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hour" type="hourType" maxOccurs="21"/>
                        </xs:sequence>
                        <xs:attribute name="bgcolor" type="xs:string" default="white"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="days">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="day" maxOccurs="7">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="row" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cell" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="break"/>
                                                                <xs:element name="course">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="courseid" type="xs:positiveInteger"/>
                                                                            <xs:element name="code">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:pattern value="([a-zA-Z])+[0-9]{3}(/([0-9])+)*"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element name="name" type="xs:string"/>
                                                                            <xs:element name="teacher" type="oneAttributeType"/>
                                                                            <xs:element name="rooms">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="room" type="oneAttributeType" maxOccurs="unbounded"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="color" type="xs:string" default="white"/>
                                                                        <xs:attribute name="note" type="xs:positiveInteger"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:choice>
                                                            <xs:attribute name="pdiff" type="xs:positiveInteger" use="required"/>
                                                            <xs:attribute name="diff" type="xs:positiveInteger" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="num" type="xs:positiveInteger" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="MON"/>
                                                <xs:enumeration value="TUE"/>
                                                <xs:enumeration value="WED"/>
                                                <xs:enumeration value="THU"/>
                                                <xs:enumeration value="FRI"/>
                                                <xs:enumeration value="SAT"/>
                                                <xs:enumeration value="SUN"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="rows" type="xs:positiveInteger"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="notes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="note" type="oneAttributeType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="num" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xbacinsk/MZJ_Timetable/misc/test.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="timetable.xsl"?>

<timetable xsi:noNamespaceSchemaLocation="timetable.xsd" xmlns=""
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <hours bgcolor="d5f9d2">
        <hour pdiff="8" diff="12">08:00</hour>
        <hour pdiff="7" diff="12">09:00</hour>
        <hour pdiff="7" diff="12">10:00</hour>
        <hour pdiff="7" diff="12">11:00</hour>
        <hour pdiff="7" diff="12">12:00</hour>
        <hour pdiff="7" diff="12">13:00</hour>
        <hour pdiff="7" diff="12">14:00</hour>
        <hour pdiff="7" diff="12">15:00</hour>
        <hour pdiff="7" diff="12">16:00</hour>
        <hour pdiff="7" diff="12">17:00</hour>
        <hour pdiff="7" diff="12">18:00</hour>
        <hour pdiff="6" diff="10">19:00</hour>

    </hours>
    <days>
        <day id="Po" rows="1">
            <row num="1">
                <cell pdiff="31" diff="48" >
                    <break/>
                </cell>
                <cell pdiff="6" diff="10">
                    <course>
                        <courseid>632905</courseid>
                        <code>PB138/5</code>
                        <name>Moderní značkovací jazyky</name>
                        <teacher id="60380">A. Rambousek</teacher>
                        <rooms>
                            <room id="4384">B130</room>
                        </rooms>
                    </course>
                </cell>
                <cell pdiff="40" diff="62">
                    <break/>
                </cell>
                <cell pdiff="14" diff="22">
                    <course>
                        <courseid>632862</courseid>
                        <code>MB104</code>
                        <name>Matematika IV</name>
                        <teacher id="7048">Panak</teacher>
                        <rooms>
                            <room id="534">D1</room>
                            <room id="533">D2</room>
                            <room id="2362">D3</room>
                        </rooms>
                    </course>
                </cell>
            </row>
        </day>
        <day id="Út" rows="2">
            <row num="1">
                <cell pdiff="14" diff="22">
                    <course color="ffdddd">
                        <courseid>632862</courseid>
                        <code>MB104</code>
                        <name>Matematika IV</name>
                        <teacher>Panak</teacher>
                        <rooms>
                            <room>D1</room>
                            <room>D2</room>
                        </rooms>
                    </course>
                </cell>
                <cell pdiff="16" diff="26">
                    <break/>
                </cell>
                <cell pdiff="14" diff="22">
                    <course>
                        <courseid>632905</courseid>
                        <code>PB138</code>
                        <name>Moderní značkovací jazyky</name>
                        <teacher>Pitner</teacher>
                        <rooms>
                            <room>D1</room>
                        </rooms>
                    </course>
                </cell>        
                <cell pdiff="16" diff="26">
                    <break/>
                </cell>
                <cell pdiff="14" diff="22">
                    <course>
                        <courseid>632850</courseid>
                        <code>IV111</code>
                        <name>Pravděpodobnost v informatice</name>
                        <teacher>Bouda</teacher>
                        <rooms>
                            <room id="773">B204</room>
                        </rooms>
                    </course>
                </cell>
                <cell pdiff="1" diff="2">
                    <break/>
                </cell>
                <cell pdiff="14" diff="22">
                    <course>
                        <courseid>632850</courseid>
                        <code>IV111/01</code>
                        <name>Pravděpodobnost v informatice</name>
                        <teacher id="3717">J. Bouda</teacher>
                        <rooms>
                            <room>B410</room>
                        </rooms>
                    </course>
                </cell>
            </row>
            <row num="2">
                <cell pdiff="62" diff="96">
                    <break/>
                </cell>
                <cell pdiff="14" diff="22">
                    <course>
                        <courseid>632938</courseid>
                        <code>PV120</code>
                        <name>Informacni pravo</name>
                        <teacher id="1084">Smid</teacher>
                        <rooms>
                            <room id="2362">D3</room>
                        </rooms>
                    </course>
                </cell>
                <cell pdiff="15" diff="24">
                    <break/>
                </cell>
            </row>
        </day>
        <day id="Čt" rows="1">
            <row num="1">
                <cell pdiff="62" diff="96">
                    <break/>
                </cell>
                <cell pdiff="22" diff="34">
                    <course>
                        <courseid>632808</courseid>
                        <code>IA014</code>
                        <name>Funkcionální programování</name>
                        <teacher id="325">Škarvada</teacher>
                        <rooms>
                            <room id="773">B204</room>
                        </rooms>
                    </course>
                </cell>
                <cell pdiff="7" diff="12">
                    <break/>
                </cell>
            </row>
        </day>
    </days>
</timetable>

=== xbacinsk/MZJ_Timetable/misc/my_timetable.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="timetable.xsl"?>
<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="" xsi:noNamespaceSchemaLocation="timetable.xsd">
 <hours bgcolor="f5f5f5">
  <hour diff="12" pdiff="7">08:00</hour>
  <hour diff="12" pdiff="7">09:00</hour>
  <hour diff="12" pdiff="7">10:00</hour>
  <hour diff="12" pdiff="7">11:00</hour>
  <hour diff="12" pdiff="7">12:00</hour>
  <hour diff="12" pdiff="7">13:00</hour>
  <hour diff="12" pdiff="7">14:00</hour>
  <hour diff="12" pdiff="7">15:00</hour>
  <hour diff="12" pdiff="7">16:00</hour>
  <hour diff="12" pdiff="7">17:00</hour>
  <hour diff="12" pdiff="7">18:00</hour>
  <hour diff="10" pdiff="6">19:00</hour>
 </hours>
 <days>
  <day rows="1" id="MON">
   <row num="1">
    <cell diff="60" pdiff="36">
     <break/>
    </cell>
    <cell diff="10" pdiff="6">
     <course color="d9f5d5">
      <courseid>632905</courseid>
      <code>PB138/6</code>
      <name>Moderní značkovací jazyky</name>
      <teacher id="60380">A. Rambousek</teacher>
      <rooms>
       <room id="4384">B130</room>
      </rooms>
     </course>
    </cell>
    <cell diff="72" pdiff="43">
     <break/>
    </cell>
   </row>
  </day>
  <day rows="2" id="TUE">
   <row num="1">
    <cell diff="20" pdiff="12">
     <course color="e9d5e5">
      <courseid>636898</courseid>
      <code>SOC109</code>
      <name>Demografie</name>
      <teacher id="1605">Burjanek</teacher>
      <rooms>
       <room id="8368">P31</room>
      </rooms>
     </course>
    </cell>
    <cell diff="4" pdiff="2">
     <break/>
    </cell>
    <cell diff="20" pdiff="12">
     <course color="e9d5e5">
      <courseid>636893</courseid>
      <code>SOC103</code>
      <name>Obecná sociologická teorie</name>
      <teacher id="5918">Szaló</teacher>
      <rooms>
       <room id="8368">P31</room>
      </rooms>
     </course>
    </cell>
    <cell diff="4" pdiff="2">
     <break/>
    </cell>
    <cell diff="22" pdiff="13">
     <course color="e9d5e5">
      <courseid>632905</courseid>
      <code>PB138</code>
      <name>Moderní značkovací jazyky</name>
      <teacher id="94">Pitner</teacher>
      <rooms>
       <room id="534">D1</room>
      </rooms>
     </course>
    </cell>
    <cell diff="72" pdiff="43">
     <break/>
    </cell>
   </row>
   <row num="2">
    <cell diff="48" pdiff="28">
     <break/>
    </cell>
    <cell diff="18" pdiff="10">
     <course color="e9d5e5">
      <courseid>636896</courseid>
      <code>SOC106</code>
      <name>Metodologie sociálních věd</name>
      <teacher id="108207">Kreidl</teacher>
      <rooms>
       <room id="8368">P31</room>
      </rooms>
     </course>
    </cell>
    <cell diff="76" pdiff="45">
     <break/>
    </cell>
   </row>
  </day>
  <day rows="3" id="WED">
   <row num="1">
    <cell diff="48" pdiff="28">
     <break/>
    </cell>
    <cell diff="22" pdiff="13">
     <course color="d9f5d5">
      <courseid>633006</courseid>
      <code>VB036/14</code>
      <name>English II</name>
      <teacher id="2448">I. Tulajová</teacher>
      <rooms>
       <room id="891">C511</room>
      </rooms>
     </course>
    </cell>
    <cell diff="50" pdiff="30">
     <break/>
    </cell>
    <cell diff="22" pdiff="13">
     <course color="e9d5e5">
      <courseid>632936</courseid>
      <code>PV113</code>
      <name>Produkce audiovizuálního díla</name>
      <teacher id="2378">Sojka</teacher>
      <rooms>
       <room id="2362">D3</room>
      </rooms>
     </course>
    </cell>
   </row>
   <row num="2">
    <cell diff="72" pdiff="43">
     <break/>
    </cell>
    <cell diff="22" pdiff="13">
     <course color="e9d5e5">
      <courseid>632950</courseid>
      <code>PV174</code>
      <name>Laboratoř EM aplikací</name>
      <teacher id="2378">Sojka</teacher>
      <rooms>
       <room id="528">C522</room>
      </rooms>
     </course>
    </cell>
    <cell diff="14" pdiff="8">
     <break/>
    </cell>
    <cell diff="10" pdiff="6">
     <course color="e9d5e5">
      <courseid>632936</courseid>
      <code>PV113</code>
      <name>Produkce audiovizuálního díla</name>
      <teacher id="2378">Sojka</teacher>
      <rooms>
       <room id="705">A104</room>
      </rooms>
     </course>
    </cell>
    <cell diff="24" pdiff="14">
     <break/>
    </cell>
   </row>
   <row num="3">
    <cell diff="96" pdiff="57">
     <break/>
    </cell>
    <cell diff="22" pdiff="13">
     <course color="e9d5e5">
      <courseid>632986</courseid>
      <code>SIN02</code>
      <name>Sociální aspekty informatiky</name>
      <teacher id="1404">Kopeček</teacher>
      <rooms>
       <room id="892">C525</room>
      </rooms>
     </course>
    </cell>
    <cell diff="24" pdiff="14">
     <break/>
    </cell>
   </row>
  </day>
 </days>
 <notes/>
</timetable>
